#!/usr/bin/env python3
"""
Convert ComfyUI workflow JSON from comfy_api_nodes OpenAI GPT Image nodes
(OpenAIGPTImage1, OpenAIGPTImageNodeV2) to local_api OpenAIGPTImageDirect nodes.

Usage:
    python convert_openai_nodes.py input_workflow.json output_workflow.json
"""

import json
import sys
from copy import deepcopy

# Mapping of comfy_api_nodes → local_api node type
OPENAI_NODE_MAP = {
    "OpenAIGPTImage1": "OpenAIGPTImageDirect",
    "OpenAIGPTImageNodeV2": "OpenAIGPTImageDirect",
}


def _build_input(name: str, type_name: str, link, widget_name: str | None = None, shape: int | None = None) -> dict:
    """Build a ComfyUI input dict."""
    inp = {
        "name": name,
        "type": type_name,
        "link": link,
    }
    if widget_name:
        inp["widget"] = {"name": widget_name}
        inp["localized_name"] = widget_name
    else:
        inp["localized_name"] = name
    if shape is not None:
        inp["shape"] = shape
    return inp


def convert_node(node: dict) -> dict:
    """Convert a single comfy_api_nodes OpenAI GPT Image node to OpenAIGPTImageDirect."""
    old_type = node["type"]
    if old_type not in OPENAI_NODE_MAP:
        return node, None

    new_node = deepcopy(node)
    new_node["type"] = OPENAI_NODE_MAP[old_type]

    old_widget_values = list(node.get("widgets_values", []))

    # OpenAIGPTImage1 widget order (10 values):
    #   [0] prompt, [1] seed, [2] seed_control, [3] quality, [4] background,
    #   [5] size, [6] n, [7] model, [8] custom_width, [9] custom_height
    #
    # OpenAIGPTImageNodeV2 uses dynamic combo so widget order may vary.
    # We handle both by reading values positionally and defaulting safely.
    #
    # OpenAIGPTImageDirect widget order (11 values with control_after_generate):
    #   [0] prompt, [1] seed, [2] seed_control, [3] quality, [4] background,
    #   [5] size, [6] n, [7] model, [8] custom_width, [9] custom_height, [10] api_key

    def _safe_get(idx: int, default=""):
        return old_widget_values[idx] if idx < len(old_widget_values) else default

    prompt_val = _safe_get(0, "")
    seed_val = _safe_get(1, 0)
    seed_control_val = _safe_get(2, "randomize")
    quality_val = _safe_get(3, "low")
    background_val = _safe_get(4, "auto")
    size_val = _safe_get(5, "1024x1024")
    n_val = _safe_get(6, 1)
    model_val = _safe_get(7, "gpt-image-2")
    custom_width_val = _safe_get(8, 1024)
    custom_height_val = _safe_get(9, 1024)

    # --- Build new inputs ---
    # Order must match OpenAIGPTImageDirect.INPUT_TYPES (required first, then optional):
    # prompt, seed, quality, background, size, n, model, custom_width, custom_height, api_key
    # image, mask
    old_inputs_by_name = {inp.get("name", ""): inp for inp in node.get("inputs", [])}

    new_inputs = [
        _build_input("prompt", "STRING", old_inputs_by_name.get("prompt", {}).get("link"), "prompt"),
        _build_input("seed", "INT", None, "seed"),
        _build_input("quality", "COMBO", None, "quality"),
        _build_input("background", "COMBO", None, "background"),
        _build_input("size", "COMBO", None, "size"),
        _build_input("n", "INT", None, "n"),
        _build_input("model", "COMBO", None, "model"),
        _build_input("custom_width", "INT", None, "custom_width"),
        _build_input("custom_height", "INT", None, "custom_height"),
        _build_input("api_key", "STRING", None, "api_key"),
    ]

    # Map original image/mask inputs
    image_link = old_inputs_by_name.get("image", {}).get("link")
    mask_link = old_inputs_by_name.get("mask", {}).get("link")
    new_inputs.append(_build_input("image", "IMAGE", image_link, shape=7))
    new_inputs.append(_build_input("mask", "MASK", mask_link, shape=7))

    new_node["inputs"] = new_inputs

    # --- Build new outputs ---
    # OpenAIGPTImageDirect RETURN_TYPES = ("IMAGE",)
    # Slot 0 = image (IMAGE)
    # Original OpenAIGPTImage1 also returns IMAGE at slot 0, so no slot remapping needed
    # for outputs from this node. However, we still copy outputs to be safe.
    old_outputs = node.get("outputs", [])
    image_links = []

    for out in old_outputs:
        if out.get("type") == "IMAGE" and out.get("links"):
            links = out["links"]
            if isinstance(links, list):
                image_links.extend(links)
            else:
                image_links.append(links)

    image_links = list(dict.fromkeys([l for l in image_links if l is not None]))

    new_outputs = [
        {"name": "image", "type": "IMAGE", "links": image_links if image_links else None},
    ]
    new_node["outputs"] = new_outputs

    # --- Build new widget values ---
    new_node["widgets_values"] = [
        prompt_val,           # prompt
        seed_val,             # seed
        seed_control_val,     # seed_control (auto-generated by control_after_generate)
        quality_val,          # quality
        background_val,       # background
        size_val,             # size
        n_val,                # n
        model_val,            # model
        custom_width_val,     # custom_width
        custom_height_val,    # custom_height
        "",                   # api_key
    ]

    # Update properties
    props = new_node.get("properties", {})
    props["Node name for S&R"] = "OpenAIGPTImageDirect"
    # Remove comfy-core specific properties
    props.pop("cnr_id", None)
    props.pop("ver", None)
    new_node["properties"] = props

    return new_node, node["id"]


def convert_workflow(data: dict) -> dict:
    """Convert all OpenAI comfy_api_nodes in a workflow to local equivalents."""
    converted_count = 0
    converted_node_ids = {}

    for node in data.get("nodes", []):
        old_type = node.get("type", "")
        if old_type in OPENAI_NODE_MAP:
            node_id = node["id"]
            new_node, _ = convert_node(node)
            node.clear()
            node.update(new_node)
            converted_count += 1
            converted_node_ids[node_id] = True

    # Fix link target slots for converted nodes.
    # Original OpenAIGPTImage1 inputs:
    #   slot 0 = image (IMAGE)
    #   slot 1 = mask (MASK)
    #   slot 2 = prompt (STRING)
    # OpenAIGPTImageDirect inputs:
    #   slot 0 = prompt (STRING)
    #   slot 10 = image (IMAGE)
    #   slot 11 = mask (MASK)
    for link in data.get("links", []):
        if link[3] in converted_node_ids:
            if link[5] == "IMAGE":
                link[4] = 10   # image now at slot 10
            elif link[5] == "MASK":
                link[4] = 11   # mask now at slot 11
            elif link[5] == "STRING":
                link[4] = 0    # prompt now at slot 0

    print(f"Converted {converted_count} OpenAI GPT Image node(s).")
    return data


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} input.json output.json")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(input_path, "r") as f:
        data = json.load(f)

    data = convert_workflow(data)

    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Saved converted workflow to {output_path}")


if __name__ == "__main__":
    main()
